- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: docker, tags: [ 'docker']}
  - { role: ntp, tags: [ 'ntp']}
  # - { role: linux, tags: [ ' werkt volgens jullie niet, dus er is niets te zien.']}

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: windows_ssh, tags: [ 'ssh']}
  - { role: windows_roles, tags: [ 'roles']}
  - { role: windows_adds, tags: [ 'adds']}
  - { role: windows_ou, tags: [ 'ou']}
  - { role: windows_agdlp, tags: [ 'agdlp']}
  - { role: windows_users, tags: [ 'users']}
  - { role: windows_shares, tags: [ 'shares']}
  - { role: windows_updates, tags: [ 'updates']}
  - { role: windows_backup, tags: [ 'backup']}
  - { role: windows_restore, tags: [ 'restore']}

- hosts: Werkstations
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: werkstations, tags: [ 'werkstations']}
  - { role: windows_apps, tags: [ 'apps']}
  - { role: windows_ai_nvidia, tags: [ 'nvidia']}
  - { role: windows_ai_amd, tags: [ 'amd']}