- name: include the firewall rules vars
  ansible.builtin.include_vars:
    file: host_vars/windows_firewallvars.yml


- name: add the firewall rules
  ansible.windows.win_firewall_rule:
    name: "{{ item.key }}"
    description: "{{ item.value.description }}"
    direction: "{{ item.value.direction }}"
    localport: "{{ item.value.localport }}"
    protocol: "{{ item.value.protocol }}"
    action: "{{ item.value.action }}"
    enabled: "{{ item.value.enabled }}"
  loop: "{{ lookup('dict', 'firewall_rules') }}"